name: cuid2018
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - scipy
  - cv2
  - opencv-contrib-python
  - scikit-image
  - sympy
